### ISSUE TITLE
Long standing Retroshare File Sharing issues and needs to be added and addressed

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#1016]
**Long standing Retroshare File Sharing issues and needs to be added and addressed**

The Retroshare File Sharing ability is a vital function on Retroshare. For the past 5yrs I have repeatedly requested, requested, outlined and posted these requests, suggestions and outlined their benefits to the Retroshare developers, Retroshare developers chat room visitors and developers, Retroshare developers forum and issues board.

**Meanwhile download ratios or how often that file has been downloaded is still not added.**

**Alt-Name download field is still not added.**

**Password optional field is still not added**

**Category field is still not added.**

**Place .torrent file download into a optional directory is still not added**

**Add a SQL database tie to files offered for .torrent file sharing**

**Add the ability to download sqlite linked retroshare shared files db directly into a database reader**

**Add the direct connection to connection (true peer to peer) ability, not the current smoke and mirrors relayed high loss overhead turtle networked faux direct connection F2F.**

**Add optional scheduled bandwidth changes based on times of day, day of the week.**

**Re-code the ability to keep the user set bandwidth UL/DL to those values or lower, never allow them to grow higher than what the user manually sets.**

**Add optional folder 2 way sync with a directly added friend. Coding for a 1 way sync with a subscriber of a Retroshare Channel already exists.**

 **Add a Category ID or a Group ID so Retroshare larger files can be instantly seeded to those subscribers having chosen that Category ID or Group ID.** This is not 'Circles', not local 'Groups'. The Circle coding logic appears to be confusing even the Retroshare application itself forcing Circles administrators to spend a great deal of time eliminating any Circles they created to make certain to return data control back to them that is being diverted to hosting other Circles data they were not even subscribed nor part of. Category ID's would provide a base of 10-100 users to all share the same larger video files on the Retroshare file sharing network that is woefully slow attempting to share the same file from a single source.

**Comment by felisucoibi** [comment]
Like always not focusing, i don't agree of the priority of almost any of your "5 years" ideas.... and your ideas are not explained here, so makes no sense to put them here in github, the only reason to put them here is because we banned you in rs forums and nobody is listening....

"Meanwhile download ratios or how often that file has been downloaded is still not added."
Something optional, can be useful, but not a priority.

"Alt-Name download field is still not added."
??

"Password optional field is still not added"
??

"Category field is still not added."
??

"Place .torrent file download into a optional directory is still not added"
?? this is retroshare not bittorrent ???

"Add a SQL database tie to files offered for .torrent file sharing"
?? hello?

"Add the ability to download sqlite linked retroshare shared files db directly into a database reader"
?? all the p2p software does.... why dont we?? ironic.... 

"Add the direct connection to connection (true peer to peer) ability, not the current smoke and mirrors relayed high loss overhead turtle networked faux direct connection F2F."
It's working for me at max speed, which kind of connection you have that your upload speed is no all used?

"Add optional scheduled bandwidth changes based on times of day, day of the week."
A priority of course.... (ironic)

"Re-code the ability to keep the user set bandwidth UL/DL to those values or lower, never allow them to grow higher than what the user manually sets."
Agree.

"Add optional folder 2 way sync with a directly added friend. Coding for a 1 way sync with a subscriber of a Retroshare Channel already exists."
This needs a new module itself, is not file sharing stuff, is a new module that can be coded, but not in files module.


"Add a Category ID or a Group ID so Retroshare larger files can be instantly seeded to those subscribers having chosen that Category ID or Group ID. This is not 'Circles', not local 'Groups'. The Circle coding logic appears to be confusing even the Retroshare application itself forcing Circles administrators to spend a great deal of time eliminating any Circles they created to make certain to return data control back to them that is being diverted to hosting other Circles data they were not even subscribed nor part of. Category ID's would provide a base of 10-100 users to all share the same larger video files on the Retroshare file sharing network that is woefully slow attempting to share the same file from a single source."
This is against rs filosophy, and legally can put people in troubles, i don't like at all, just wait people connections are better for a f2f network and use bittorrent like is being used for videos etc like popcorn stuf...

**Comment by ASmith-** [comment]
Normally a responder should have at least a clue as to what is being suggested, requested or stated before posting here. Apparently that professionalism is entirely lost with you.

I created and own nearly 12 Retroshare forums, a half dozen Retroshare chat rooms and a half dozen channels in Retroshare. I discuss various enhancements and needs by Retroshare routinely with the lead developer of Retroshare Cyril and have done so for the past 5 years on this project. Your spew about banning me on Forums is Bull Shit, you are not a developer and your suggestions are often childish at best, you have a great deal of growing up and maturity to somehow gain before making such rash statements.

In order for the Retroshare File Sharing Network as it stands now to fully be able to share larger video sized files with realistic bandwidths to the distant peers, there must be multiple sources of that file available. I created the Retroshare File Sharing Network Seeding Channel to help address that woeful need which has existed on the Retroshare File Sharing Network since day ONE. Having 10 or more sources of a large file to help provide bandwidth via the Retroshare swarm coding plus further optimal routing to that peer on the Turtle Routed Network is essential. A collaborative category ID like the Retroshare Circles would serve to meet that need.

**Comment by dtschmitz** [comment]
crickets

**Comment by felisucoibi** [comment]
that's troll behabour, first touch the balls spaming everywhere for months or years, after that when somebody tells you the truth you get ofended and cry and expect people to understand you, obviously new commers not the people that knows you... you did shit in RS, yo do everyday, spamming all the forums, all the threads all the time everyday and now spamming with your crap in github... because nobody listen to you in forums and lot of people banned you.... your bugs reports or whatever they are in github are shit, no explanations just text without nonsense again and again and again.... like you do in forums or in chats inside rs...

**Comment by ASmith-** [comment]
Yes you are trolling this issue, issuing trash remarks and then expect them to fly. I found and reported the largest outside attack on Retroshare to date on the Retroshare Project and pinpointed where the attack was coming from and what they were doing exactly, to the lead Retroshare developer. That was long before you came to Retroshare staggering around like a drunk in a china shop spewing all manner of claims and demands.

If you had run the Sqlite DB reader as I had some 2 years ago now to inspect and report on the fields and copious records I found in the Forums, Channels you'd have some idea what I was talking about in the parent thread of this long standing File Sharing issues but you were not even a user on Retroshare at that time even if you used a non-windows system to run the sqlite DB reader and inspect the existing Retroshare database fields and records. So you are drawing a blank on those added fields and why they should be added. Its not for me to explain to you what the developers on this project already know and I have already spoken to about this need here.

Would Retroshare source code sqlite config linkage even exist today if I hadn't posted and pushed others to do that manually?
Would I2P even been added without all of the pro's and cons being listed and the push for that as well?
Would PFS have been added without all of the discussion brought forth on that need?
Would the option of 4096bit keys have been added without all of the push for that?
Would signed chat rooms and forums have been added without all of the push for that?

I have handed out more copys of the steps to create a bug report using gdb to new Retroshare users than I can count in my IRC retroshare chatrooms which I own and created and relay linked together. I own and created a dozen Retroshare Forums and use the ones I created to post updates that are specific to either the Retroshare project or to that specific Forum.

I routinely post bug reports in the Retroshare signed Bug Forum and here in the Github Issues. If the bug is particularly acute, I'll post it also in the Retroshare Developers signed forum and in the Retroshare Developers signed chat room for immediate review as well.

My positive rating is among the highest on Retroshare. If someone such as yourself bans me, that is your loss, not mine.

**Comment by dtschmitz** [comment]
Ptewey

**Comment by felisucoibi** [comment]
Yours is bigger its ok, n anyway you are wasting everybodys time.

**Comment by dtschmitz** [comment]
Smithy has been spamming on RS going back five years to when I first began following its development at 'Linux Advocates'.  He is a 'legend in his own mind'.  Just ask him. LOL ;)
