### ISSUE TITLE
BUG Regular Retroshare Nodes sharing the same router do not connect to one another

### ISSUE THREAD

**Issue by ASmith-** [RetroShare/RetroShare#1196]
BUG Regular Retroshare Nodes sharing the same router do not connect to one another

Regular Nodes using the same router are now once again unable to connect to one another. This is a really old bug that surfaces from time to time and once again has suddenly reared its head during this Feburary's 2018's commits to the source code. Its disappointing to see your own nodes unable to connect to one another like this on different systems but sharing the same router.

This only effects the Regular Retroshare Nodes, not the Retroshare Hidden node via Tor whose Socks5 tor Proxy connects with each of the Retroshare Regular nodes but the Regular Nodes do not connect to one another.

**Comment by G10h4ck** [comment]
I am running both 0.6.3 nodes and current master branch nodes and cannot reproduce this bug my nodes connects well with their LAN address, what we still miss is some kind of automatic discovery in local LAN taking advantage of multicast, but usually LAN peers manage to connects anyway because of discovery2 or certificate exchange anyway

**Comment by ASmith-** [comment]
Working once again, no idea if anything changed.
