### ISSUE TITLE
Xfce no tray icon is showed.

### ISSUE THREAD

**Issue by kv-gits** [RetroShare/RetroShare#1297]
On xfce there is no tray icon and if to close RS It will hangs in background.

xfce4-panel 4.12.0 (Xfce 4.12), ubuntu 16.04, 

RS tor-only appimage

**Comment by G10h4ck** [comment]
Does Xfce implement opendesktop specifications?

**Comment by G10h4ck** [comment]
Does Xfce implement opendesktop specifications? This problem usually happens in desktop environements which does't implement tray bar. Because of that by default RetroShare 0.6.5 have minimize to tray icon option disabled by default, so I suggest to you to update and change that setting in RetroShare options
