### ISSUE TITLE
Enhancement: distribute in Flatpak via Flathub

### ISSUE THREAD

**Issue by HalisCz** [RetroShare/RetroShare#1326]
I was pleasantly suprised by the number of supported (e.g. there is package for them) Linux distributions.

Have you been thinking about releasing RetroShare as a [Flatpak](https://en.wikipedia.org/wiki/Flatpak), possibly via [Flathub](https://flathub.org/home)?

**Comment by G10h4ck** [comment]
I haven't experience with flatpack but contribution on that direction are welcome!

**Comment by vogelj** [comment]
i recently made a flatpak manifest for retroshare for personal use. If anybody is interested in using it or submitting it to flathub and maintaining it, feel free.
https://gist.github.com/vogelj/dbf4772cc3a54371ef89360ed87bdf56

**Comment by G10h4ck** [comment]
I have opened a PR to flathub admins with the file you shared almost unmodified https://github.com/flathub/flathub/pull/1129

Thanks!

**Comment by Nokia808** [comment]
@G10h4ck 
Dear do you noticed that there are errors in current flatpak package on FlatHub testing repositories, that need fixes before merge it ? I will put them bellow since I notice that there was no response from your side ! They are reported by @nedrichards as following:



    libGL error: MESA-LOADER: failed to retrieve device information
    libGL error: Version 4 or later of flush extension not found
    libGL error: failed to load driver: i915
    libGL error: failed to open drm device: No such file or directory
    libGL error: failed to load driver: i965

You need to add --device=dri to your finish-args to fix this.

Best wish & thank you very much to providing this great software as flatpak on FlatHub !

**Comment by G10h4ck** [comment]
Thanks for reminder

**Comment by Nokia808** [comment]
I see it merged now ! Thank you for making this diamond available in FlatHub for almost all Linux users !

**Comment by G10h4ck** [comment]
Let's keep this bug open until 0.6.6, and also until we add flathub in our website too

**Comment by Nokia808** [comment]
@G10h4ck 
Hi all ! Version 0.6.6 was already released, but till now this issue is still opened ! Moreover, I noticed the following 2 bad things:
1) till now you did not add, to your web site, link to flatpak version that already posted on FlatHub !
https://www.flathub.org/apps/details/cc.retroshare.retroshare-gui
2) moreover, the flatpak version package on FlatHub is out of date !! Till now not updated to version 0.6.6 ! Moreover, Tor bundle is still out of date - something very bad from security point of view !

**Comment by G10h4ck** [comment]
Just added the link to our Flatpak on the download page on our website, I hope I have time soon to provide a flatpak for RetroShare 0.6.6 both GUI and service.
