### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by princekelly1** [RetroShare/RetroShare#1373]
Hello, I'm Kelly. 
I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.
And maybe a FAQ document, if I may

**Comment by csoler** [comment]
hi Kelly. 
RS doesn't collect much information, since it allows you to use any name as login and has strictly no point of centralization. Besides, if using the Tor version, your IP will be totally hidden even from your friends. So there's no real privacy issues involved. We published a blog post about privacy a while ago (see https://retroshareteam.wordpress.com/2013/01/06/privacy-on-the-retroshare-network/) but it's 5 years old and would need to be updated a little bit in order to account for hidden nodes.
Could you ellaborate a bit about what you would write?

**Comment by princekelly1** [comment]
Hi
I just checked from the link you sent, it seems advanced, as you said it might need some updating. 
Would you like some FAQ documentation?

**Comment by csoler** [comment]
There's one FAQ already mentionned on the retroshare.net website, that probably needs to be updated. It's here http://retroshare.sourceforge.net/wiki/index.php/Frequently_Asked_Questions. If you're familiar with the software, you're welcome to update this FAQ. Would be better to have a short version that we can embed into retroshare.github.io website, instead of this old one that is too big.

**Comment by princekelly1** [comment]
OK, I will check and see if more can be added or updated
