### ISSUE TITLE
Where can download the latest version of retroshare including ipv6 function?

### ISSUE THREAD

**Issue by tangdou1** [RetroShare/RetroShare#1387]

**Comment by G10h4ck** [comment]
Which flavor of retroshare do you need ( retroshare-gui/retroshare-service/retroshare-nogui/...) for retroshare-service there is an experimental package in our OBS repositories, called retroshare-service-git, for retroshare-gui if you have ubuntu or similar distribution Cyril maintain the unstable PPA that should include both retroshare-gui and retroshare-nogui packages with IPv6 support, otherwise you can get the source from our git repository and compile it
