### ISSUE TITLE
Offline mail not implemented?

### ISSUE THREAD

**Issue by etam** [RetroShare/RetroShare#1461]
On the main website (http://retroshare.net/) mail is described:

>Send encrypted messages to other members of the network. Retroshare securely stores messages on friends' nodes to deliver messages while you're offline.

On the features list (https://retroshare.readthedocs.io/en/latest/#features) mail is described:

>Send encrypted messages to other members of the network. Retroshare can store encrypted messages on friends nodes to deliver messages while you're offline.

I've tried to find how this works and all I found is that it does not.

I couldn't find any technical documentation about it nor any code that might implement it. Instead I found this:

https://github.com/RetroShare/RetroShare/blob/3b6bac2d9b6ca84c52c7f14beaf60ebf8368cb13/libretroshare/src/services/p3msgservice.cc#L379-L381

I tried to test it, but instead I reproduced #613.

If that's really the case and I haven't missed anything, then I think the feature description should be adjusted, with at least a note that the offline feature is planned, but not implemented yet.

**Comment by csoler** [comment]
you've been confused by the 2 different mail systems that exist in v0.6.4: one that sends messages to friend nodes (the code you're citing, which doesn't work offline) and one that send messages to identities you see in People tab (which does). Both are accessible in Mail and depend on wether you select an identity or a friend node. 
Because this was really confusing to new users, we only keep the offline mail in upcoming v0.6.5

**Comment by etam** [comment]
Well, indeed it works. And this thing with identities is really confusing.

As a test environment I set up 3 virtual machines, connected to a single host-only network. After exchanging keys nodes were connected to each other, but there was no entries in People tab. Only after I exchanged some messages between them through chat, identities appeared in People tab.

Do you have any pointers to some details about how it works?
