### ISSUE TITLE
I just want to remember that private messages are broken, and direct chat is disabled for 0.6.5, NOT GOOD.

### ISSUE THREAD

**Issue by felisucoibi** [RetroShare/RetroShare#1466]
I just want to remember that private messages are broken, and direct chat is disabled for 0.6.5, NOT GOOD.
Just in case devs forgot private chats are not working properly, and direct chats are disable after a gohack PR one month ago.

Reeable direct chats for 0.6.5 because i'sure by now private chats are not going to work properly till at least 0.6.6....

PLEASE, DO NOT RELEALSE 0.6.5 AFTER THIS IS REVERTED.
Bests, mr nobody.

**Comment by defnax** [comment]
yes they remove/cut working features which is really needed.
Instead making easy hybrid version no, all will be removed. sad but true .
They can implement like Konrads Emoty he found how to mix inteligeny use both.
https://github.com/Emotyco/Emoty-Desktop

The Friend to friend idea goes to be removed

- technical names
- no direct chat
- no direct mail
- no public group chat

as you wanted easy retroshare the direction goes to be difficult rs for the experts only.
we did improved in the past lots to make rs easy.

GXS distant chat has lots of disaadvantages 
Instead of work to improve distant chat, but disable it easyer via one if def.

Distant Chat:
- You cant chat more with your direct friend
- User must online to chat and connected via tunnel (instable)
- no offline chat messages possible
- no status (Online, Away, Busy,...)
- no status strings

best is use old versions

**Comment by felisucoibi** [comment]
fixed by now.
