### ISSUE TITLE
Very buggy on Arch - cannot use it anymore

### ISSUE THREAD

**Issue by tiotrom** [RetroShare/RetroShare#1587]
I use: Manjaro Gnome
This is how my retroshare looks like:
![2019-06-21_17-00](https://user-images.githubusercontent.com/34804533/59932174-ead59c00-9446-11e9-858e-6f663e306a76.png)
Installed from https://aur.archlinux.org/packages/retroshare

**Comment by tiotrom** [comment]
Ok so I had to drag from right side to make the left buttons smaller to see the rest....but still the other graphical issues why are they happening?

**Comment by G10h4ck** [comment]
did you have same problem with retroshare package from our repository?  http://retroshare.cc/downloads.html#archlinux

**Comment by tiotrom** [comment]
No, I did not test that one I thought AUR is the official version of retroshare. Should I report to AUR then? Cheers!

**Comment by G10h4ck** [comment]
The AUR version is independently maintained by @sehraf he does a great job and we are grateful to him, also we link his version on our download page as an alternative. Before you report to him as an AUR specific issue, please test the package on our repository, to determine if it is a general issue with RetroShare or just with the AUR build. Looking at the screenshot you provided it is probably a general issue of RetroShare-gui + you desktop environment, on Gentoo with KDE Plasma my RetroShare-gui is not deformed, but I get those annoying one icon little windows too, @aleixpol suggested to me to use gammaray to investigate the bug but still I had no time for that since my contributions are mainly to libretroshare and not to the GUI.

**Comment by tiotrom** [comment]
For the past 2 days no such issues occurred. So I will keep an eye on it. If I see the same errors I'll try that version too. Thank you for your work!
