### ISSUE TITLE
plugins corrupt? VOIP.dll, FreeReader.dll

### ISSUE THREAD

**Issue by ralfhauser** [RetroShare/RetroShare#159]
Just downloaded the newest Windows (v0.6.0x R8551) with Plugins and got 2 error messages about missing registration.
2) I skipped that part and looked it up in Options, PlugIns - as per the attached screenshot.
The "About" button for both doesn't work :(

Any hints?

![image](https://cloud.githubusercontent.com/assets/1681677/10714283/c14d999a-7ae7-11e5-90f1-162fafb42e5b.png)

**Comment by electron128** [comment]
No, the plugins are not corrupt. The are just disabled. Because of this they are not loaded. It is not possible to show an about page for a plugin which is not loaded.
The about button should be hidden for not loaded plugins. I will fix this. I will also add better labels. "Title unavailable Unknown Version Description unavailable" is not nice.

The error message you saw is not an error message. It is a message box to ask the user if he wants to load this plugin. In my opinion this message box is bad. Because it has a complicated text and uses complicated words like "hash" (who can explain grandma what a hash is?). And with multiple plugins installed the message box gets annoying.

**Comment by electron128** [comment]
about button for unloaded plugins is disabled in  b340d8a

**Comment by ralfhauser** [comment]
3) it would be great to have a "lazy/late load button" to load the plugin hash once I stumble over this message.
Even better if there were a https web-page (or pgp-signed?) that list all the available plugins and their hashes

**Comment by ralfhauser** [comment]
4) Also, it would be great to have a further info link on the first warning page where the user encounters the topic
![freereaderplugincorrupt](https://cloud.githubusercontent.com/assets/1681677/10716301/bf0b114c-7b34-11e5-91a5-8b4226ffdbd3.png)

**Comment by ralfhauser** [comment]
5) The water dripping effect on the "About" page of the program is very nice.
But it would be great to have an easy way to copy the exact version string "v0.6.0x R8551" into the clipboard

**Comment by chozabu** [comment]
@ralfhauser re:5)
How about the copy info button below the water?
![](http://chozabu.net/autopush/2015-10-25-15-47-762633255.png)

**Comment by ralfhauser** [comment]
@chozabu  Such a "Copy info" button would be nice. It doesn't exist yet on the current windows version.
![nocopybutton](https://cloud.githubusercontent.com/assets/1681677/10720695/1c73db38-7b9a-11e5-9681-9f3233a9b2e4.png)
Alternatively, a right-mouse-click context menu offering "copy version info string to clipboard" would be great too
