### ISSUE TITLE
Missing parameter direction on @jsonapi annotation for getFileData

### ISSUE THREAD

**Issue by jpascualsana** [RetroShare/RetroShare#1591]
Hi,

The `@jsonapi` for `/rsFiles/getFileData` has missing direction annotation for `data` parameter. It should has `in/out` definition like `@param [out] data`?

https://github.com/RetroShare/RetroShare/blob/10eeb818c87ac070b9338886356f2e1f81e9fb35/libretroshare/src/retroshare/rsfiles.h#L227

**Comment by sehraf** [comment]
As signaled by `* @jsonapi{development,manualwrapper}` (notice the **manualwrapper**) this function is handled separately in https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/jsonapi/jsonapi.cpp#L226

**Comment by G10h4ck** [comment]
I probably didn't document it on purpose, because it is a pointer **value** so the semantic doesn't really fit 100% into the classic in/out/inout categories. It is basically getting a pointer **value** (=input semantic) but then use it to write on that memory location (=output semantic). As per JSON API it is an output value, as it is handled internally the JSON API user doesn't see the pointer at all. Eventually we could put `[out]` in the documentation but I am not sure if it would be misleading to C++ API users.

**Comment by jpascualsana** [comment]
Created PR https://github.com/RetroShare/RetroShare/pull/1593
