### ISSUE TITLE
dead link to mailing list on FAQ

### ISSUE THREAD

**Issue by ralfhauser** [RetroShare/RetroShare#160]
At the bottom of
http://retroshare.sourceforge.net/wiki/index.php/Frequently_Asked_Questions , there is a link to the mailing list: http://sourceforge.net/mail/?group_id=178712 ,but when trying to follow this, I get

https://sourceforge.net/p/retroshare/mailman/ : Error 403

Read access required

**Comment by realityfabric** [comment]
I don't know if it's still active, because I only signed up for it a few days ago and haven't received any emails other than for registration, but there was a link in the [Developer's Corner](http://retroshare.sourceforge.net/wiki/index.php/Developers_Corner) on the wiki at SourceForge to the mailing list for developers: https://lists.sourceforge.net/lists/listinfo/retroshare-devel

**Comment by AsamK** [comment]
Both mailing lists are practically dead, the last mail on the devel list was three months ago.

**Comment by realityfabric** [comment]
From what I understand, a lot of the dev discussion happens in a forum inside RetroShare. I don't know how true this is.

**Comment by TheSentry** [comment]
Yes, the dev discussion is mostly happening in the RetroShare forum, but also the chat.
