### ISSUE TITLE
Build instructions for Mac OSX

### ISSUE THREAD

**Issue by jekuno** [RetroShare/RetroShare#171]
Add step by step instructions on how to build `RetroShare` on Mac OSX manually to the Readme https://github.com/RetroShare/RetroShare/blob/master/README.md
Many users would probably prefer this over using an externally provided `dmg` file.

Hint: The instructions described at https://github.com/RetroShare/RetroShare/tree/master/build_scripts/OSX are more than 4 years old.

Out of curiosity: How are the dmg releases under https://github.com/RetroShare/RetroShare/releases/ created? Does this happen fully automated on the server side or are they created manually?

**Comment by sirjenster** [comment]
Well, I am the one that builds RS06 As a non-OSX expert, there are some issues I am running into into coming up with exact instructions.  Part of the problem is that i created  a specific environment that I don't know how to duplicate in a universal way. IF you like, we can coordinate and do so. Me, with the exact knowledge on what is required.  You,  with a blank,standard system with knowledge of what is normally done or available on homebrew and such... Let me know. I am Jenster in the common retroshare lobbies... here is my latest build if you want it...  http://107.150.3.74/fun/RetroShare06-20151107.dmg  (same site as Chatasaurus_Rex chatserver)

**Comment by sirjenster** [comment]
UPDATE:

All my last important OSX patches have been added to the trunk. It will now compile on Mavericks 10.9(and probably above) without changes. Just Add add non-standard dependencies in /usr/local(i.e. /usr/local/lib + /usr/local/include).

Need some help in creating  how-to-build-from-scratch  instructions. Particularly need somebody knowledgable in " homebrew" dependencies.  What can't be done in homebrew has to be done in /usr/local.

**Comment by sirjenster** [comment]
UPDATE:

**Comment by sirjenster** [comment]
UPDATE:
temporary instructions are here..  
http://107.150.3.74/fun/OSXnotes.txt
PLEASE comment and critique..Most important, try to build and let me know if you succeeded/failed.

**Comment by sirjenster** [comment]
Good news! somebody has successfully compiled(besides me) RetroShare for OSX on Yosemite/El_Capitan!! Still some issues to deal with. Particularly testing, and coming up with a universal HOW-TO or build script... Need to coordinate efforts.. more news soon...

**Comment by sirjenster** [comment]
check out this pull request..

https://github.com/RetroShare/RetroShare/pull/214

**Comment by cavebeat** [comment]
i guess this can be closed, right?
@jekuno

**Comment by jekuno** [comment]
Sorry, I totally lost track of this thread. Yes, I think it can be closed now. Thanks! :)
