### ISSUE TITLE
Official docker image of retroshare

### ISSUE THREAD

**Issue by guglez** [RetroShare/RetroShare#1839]
Hi,

Could you please build an official docker image for retroshare?

**Comment by G10h4ck** [comment]
what do you mean official docker image?
What functionalities should this image provide?
I don't understand well the point of having a docker image with just retroshare installed, because one can just run a docker container of whatever distro she prefer and install retroshare there with a command. So I am probably misunderstanding your question.

It may be helpful for you this two Dockerfiles we use for continuous integration
https://github.com/RetroShare/RetroShare/tree/master/build_scripts/GitlabCI

**Comment by G10h4ck** [comment]
maybe related https://github.com/RetroShare/RetroShare/pull/2466
