### ISSUE TITLE
[JSONAPI] /rsMsgs/setIdentityForChatLobby didn't find nick

### ISSUE THREAD

**Issue by zeners** [RetroShare/RetroShare#2269]
I'm trying to change the current nick in a chat.lobby in webui via jsonapi. 

Based on other requests i tried the following Request against a subscribed chat-lobby with an owned identity:
`POST /rsMsgs/setIdentityForChatLobby HTTP/1.1`
`Host: localhost:9092`
`User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0`
`Accept: application/json`
`Accept-Language: de-AT,de;q=0.8,en-US;q=0.5,en;q=0.3`
`Accept-Encoding: gzip, deflate
`Referer: http://localhost:9092/index.html`
`Authorization: Basic XXXXXXXXXXXXXXX`
`Content-Type: text/plain;charset=UTF-8`
`Content-Length: 68`
`Origin: http://localhost:9092`
`Connection: keep-alive`
`Cookie: XXXXXXXXXXXXXXXXXXXX`
`Pragma: no-cache`
`Cache-Control: no-cache`
` `
`{lobby_id:xxxxxxxxxxxxxxxxxxx,nick:"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}`

Response:
`HTTP/1.1 200 OK`
`Access-Control-Allow-Headers: Authorization,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range`
`Access-Control-Allow-Methods: GET, POST, OPTIONS`
`Access-Control-Allow-Origin: *`
`Access-Control-Expose-Headers: Content-Length,Content-Range`
`Connection: close`
`Content-Length: 23`
`Content-Type: application/json`
` `
`{`
`    "retval": false`
`}`

- I dind't found where the parsing of the `RsGxsId nick` take place to debug it.
- Log-Output: `(EE) Ignore empty nickname for chat lobby 00000000000000000000000000000000`
- I'm assuming that the lobby_id is successfully parsed, because it is checked before the nick

Running against a current retroshare-build: 
RetroShare Version: 0.6.6-RC2-254-g42dd13b0e
Manjaro Linux QT 5.15.2

libretroshare
 - bzip2: 1.0.8, 13-Jul-2019
 - OpenSSL: OpenSSL 1.1.1i  8 Dec 2020
 - SQLite: 3.33.0
 - SQLCipher: 4.4.2 community
 - UPnP (MiniUPnP): 2.1.20191224
 - Zlib: 1.2.11

to reproduce, you may use my webui repository https://github.com/zeners/RSNewWebUI/commit/0f920f6ab20ba0402de24607c75a5387de5851e4 and logon, switch to chat, select a subscribed lobby, use the cog wheel near lobby name and click on one of the offered identites. You will find a request similar to the one above in the networking-tab in the debugging-tools of the browser.

Is the request incorrect or is there a problem in retroshare?

**Comment by defnax** [comment]
@G10h4ck @csoler @sehraf

**Comment by sehraf** [comment]
What request are you sending?

`lobby_id` is either a (long) int or the "new" format
```json
    {
      "xint64": 7555643923972859000,
      "xstr64": "7555643923972858789"
    },
```
(see also "JSON API quirks" in "Developers Discussions" (github doesn make this clickable .. retroshare://forum?name=JSON%20API%20quirks&id=8fd22bd8f99754461e7ba1ca8a727995&msgid=15f13585e1f174d4ed998687c231f4c6e09d6cf8 ))

The `nick` is a string (id hash). So your request looks good to me, as long as the field names are string (`nick` vs `"nick"`, this makes a difference when using curl.

I was able to do this successfully using this payload:
```json
{"lobby_id": 7555643923972858789, "nick": "1b95d9a2f6762dae2c1f2fd338d47c4f"}
```
With `lobby_id` using the "simple" int.

---
```
curl -u "test:tset" -d '{"lobby_id": 7555643923972858789, "nick": "1b95d9a2f6762dae2c1f2fd338d47c4f"}' http://127.0.0.1:9092/rsMsgs/setIdentityForChatLobby 2>/dev/null| jq 
{
  "retval": true
}
```

**Comment by zeners** [comment]
omg, attributes in ",great thanks - it works, don't know how to overview that

**Comment by G10h4ck** [comment]
@zeners because webui is written in JavaScript and it doesn't supports 64bit integers you need to encode those like this:

 `"lobby_id":{"xstr64": "75556999303039489"}`

otherwise it may just silently fails depending on the value because JS internally stores big integers with floating point representation

while with curl it would work also with the plain integer representation because there is no JavaScript involved, this happens also with other languages which lack supports for 64 bit integers like Dart

Also please ping me explicitly for JSON API stuff as i don't receive notifications for issues otherwise

**Comment by G10h4ck** [comment]
It would be great to add a section explaining the 64bit quirk here https://github.com/RetroShare/RetroShare/blob/master/jsonapi-generator/README.adoc

When I wrote the code to handle this i left a bit of documentation too
https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/serialiser/rstypeserializer.cc#L140
https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/serialiser/rstypeserializer.cc#L219

But in the README it would be much more accessible

So JSON API always output 64bit integers this way

`"lobby_id": { "xint64": 6215642878098695544, "xstr64": "6215642878098695544" }`

So from languages that have proper 64bit integers support like Python or C++ one better read from `xint64` which is represented as a JSON integer, from languages where there is no proper 64bit integers support like JavaScript or Dart one can read from `xstr64` which is represented as JSON string.


When one send a 64bit integer to the JSON API it first try to parse it as if it was sent the old way for retrocompatibility:

`"lobby_id":6215642878098695544`

 this way is not recommended and may disappear in the future, it is kept only for retrocompatibiliy with old clients.

If retrocompatible parsing attempt fail then it try to parse with the new way with proper JSON integer format

`"lobby_id": { "xint64": 6215642878098695544 }`

if this fails then it it try to parse with the new way with JSON string format

`"lobby_id": { "xstr64": "6215642878098695544" }`

BEWARE clients written in languages without proper 64bit integers support must use ONLY the latter notation

`"lobby_id": { "xstr64": "6215642878098695544" }`

otherwise they will send approximated values and get unexpected results from the JSON API, because parsing will success but the value will not be exactly the one you believe you sent

**Comment by zeners** [comment]
@G10h4ck thanks, but the id itself wasn't the problem. I simply forgot the double quotation marks around the attribute names.

I will look for the usage of ids and harmonize it to the new `{"xstr64": "..."}` format.
