### ISSUE TITLE
Hidden noder over tor automatically 

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#2859]

**Comment by csoler** [comment]
If the "outgoing" led is green, it should be enough for you to connect to other Tor nodes. 

If some of your friends are clear nodes, you need to make sure they have your (new?) Tor hidden address (send your certificate), because connections only happen from clear to hidden nodes (this avoids the need for exit nodes along the way).

You can try to add the following node as friend, I'll tell you if I see any connection attempt:

ABDj9KHTob+RZ+C7D42nFjOSAxQJ/BCO0W0fkbUVBzq+yOEUAZ23LwELdGVzdC10b3ItdjOQRAAAAAImlnF0eWJneWZwNmd4dmN4
emtyM3JqY3Zqb2d6azI3d3d0Y2hxYXZ2azVwM2F6ZW9wZHRubG5lN3FkLm9uaW9uBAOpvXU=

**Comment by completlyclueless77** [comment]
have added you 1 min ago ,tell me the results pls

**Comment by csoler** [comment]
I see a connection attempt from profile 8C22...

**Comment by csoler** [comment]
SSL ID: fff82e5...  If that's you , then it works.

**Comment by completlyclueless77** [comment]
yeah thats me, but i wonder why still no one is connected with me .....
