### ISSUE TITLE
windows build using new filename for retroshare executable

### ISSUE THREAD

**Issue by pl4hh** [RetroShare/RetroShare#293]
don't know if its by design, but the latest windows build use a different name for the RS executable,
retroshare06.exe instead of retroshare.exe. 

so if you install the latest version over the old version you still have the old executable file
and any links to that exe still exist and might confuse user, since they click on their linked
icons and get the old version started instead of the new version.

using portable install if that is of any concern.

**Comment by felisucoibi** [comment]
I don't really know if I'm wrong because i use linux but... retrosare.exe is for retroshare 0.5 and retroshare06.exe is for retroshare 0.6, they are incompatible so the old config is not going to work and networks are also differents, so maybe I'm wrong but I think also in windows the right name is retroshare06.exe because is the universal name for the actual version...

But maybe I'm worng and in windows even 0.6 versions used retroshare.exe ...
