### ISSUE TITLE
Qt Interface scaling / compiling on OSX

### ISSUE THREAD

**Issue by savchenko** [RetroShare/RetroShare#304]
Scaling of numerous interface elements is wrong. 
<img width="774" alt="screen shot 2016-03-12 at 21 11 57" src="https://cloud.githubusercontent.com/assets/300146/13723158/1494cb6a-e897-11e5-8306-715413b23f1f.png">
<img width="793" alt="screen shot 2016-03-12 at 21 09 00" src="https://cloud.githubusercontent.com/assets/300146/13723152/ec36f4e0-e896-11e5-968c-9125e8c7bf95.png">

Build instructions mentioned https://github.com/RetroShare/RetroShare/issues/171 (http://107.150.3.74/fun/OSXnotes.txt) are referring to the very specific versions of microhttpd, etc. Are these enforced? Do we have automated builds running somewhere? Build instructions in the repo are [~4 years old](https://github.com/RetroShare/RetroShare/tree/master/build_scripts/OSX). Thanks.

**Comment by csoler** [comment]
that is because thre still a lot of absolute size calls such as "widget->setSize()" or
"widget->setMinimumSize()" etc. We try to get rid out of them, but it's a long way to go. 

On 12/03/2016 08:15, asvc wrote:

> Scaling of numerous interface elements is wrong.
> screen shot 2016-03-12 at 21 11 57
> https://cloud.githubusercontent.com/assets/300146/13723158/1494cb6a-e897-11e5-8306-715413b23f1f.png
> screen shot 2016-03-12 at 21 09 00
> https://cloud.githubusercontent.com/assets/300146/13723152/ec36f4e0-e896-11e5-968c-9125e8c7bf95.png
> 
> Build instructions mentioned #171 https://github.com/RetroShare/RetroShare/issues/171
> (http://107.150.3.74/fun/OSXnotes.txt) are referring to the very specific versions of microhttpd,
> etc. Are these enforced? Do we have automated builds running somewhere? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RetroShare/RetroShare/issues/304.

## 

To secure your emails, use PGP (e.g. enigmail on thunderbird)
My key: 0xD1F93BE3 http://pgp.mit.edu/pks/lookup?op=get&search=0xA4BD76DED1F93BE3

**Comment by sirjenster** [comment]
Phenom wrote some notes based on mine  and are in the first level of the trunk. My builds are based on Mavericks, which makes a build more deployable over a broader range of OSX versions. Phenom's instructions are based on Yosemite, which is easily adaptable...

https://github.com/RetroShare/RetroShare/blob/master/MacOS_X_InstallGuide.txt

as far as scale/size. most things are resizable. give it a shot...

Keep in mind Phenom and I are not OSX/GUI experts by any means. Linux/Unix is our forte. Ergo, we are more dedicated to getting things actually working properly rather than aesthetically. We are also building on hardware/environments that are limited in being able to test in. If you have expertise in QT, GUI and OSX coding, your help, in where we fall short, would be much appreciated.
