### ISSUE TITLE
Chess plugin for RetroShare

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#36]
it would be nice to get work Chess on rs network.
to play with Friends or with Friends of Friends ( with dIstant peers gxsid)

there is always started project seems not continued.
Play Chess with Online Friends start from FriendsList or from Chat lobbies with Online People.

unfinished source:
https://github.com/RetroShare/RsChess

**Comment by SarcoRS** [comment]
Asked if this is possible in internal RetroShare forums some time ago, it's good that you carved it in stone here as issue.

After using RetroShare for a while, I must say that I'm not sure this will work fine with distant peers GXSIDs. With direct friends - it probably will, but with tunnel through many peers - I would expect latency issues which will ruin time counting for short games. I am basing my expectations on experience with private chats: sometimes it takes ages to establish a private chat tunnel to somebody who isn't your direct friend. And then it casually gets broken and both sides need to wait till the tunnel is rebuilt again. Sometimes private chats don't establish the two-way tunnel handshake at all (I believe it's fair to say this after waiting for 30 minutes with no result, that's not how instant messaging works).

However, if the Chess plugin ever reaches an alpha status, perhaps it could use the Messages system as well, so this variation will be like "chess via email" rather than "interactive chess".

Anyway, a working Chess plugin can serve as additional incentive for people who want to play to exchange certificates and become direct friends.

**Comment by csoler** [comment]
I agree.

The more I think about it, the more I am inclined to implement a generic
encrypted tunnel service.
Wouldn't be difficult at all actually.

For a chess [;ugin, it is important to make sure that both players have
the same game state. Beyond that, it's quite easy to do: maintain tunnel
to other peer, exchange game packets through virtual peer id.

**Comment by chozabu** [comment]
@csoler what exactly do you mean by "a generic encrypted tunnel service"?
As in an easy function to send RsItems?
To send arbitrary serialised data?
Or to forward a regular network port - for external apps and games?

I'm really interested in the latter two!

**Comment by csoler** [comment]
To send arbitrary data. The tunnel service handles authentication and
encryption.
For now such a thing exists in distant chat. We just need to make it
more generic.
The turtle router already provides a tunnel service to send arbitrary
data. But tunnels are not
encrypted.

**Comment by chozabu** [comment]
made a quick n dirty chess plugin: https://github.com/chozabu/RetroChess

**Comment by defnax** [comment]
whats the status?
