### ISSUE TITLE
Implement ECC public keys for Short keys (easy short RetroShare ID)

### ISSUE THREAD

**Issue by defnax** [RetroShare/RetroShare#443]
Implement ECC public keys for Short keys (easy short RetroShare ID)

Easy short keys for rs. it makes more easyer for make friends.

Tox or Ring has short keys example
![image](https://cloud.githubusercontent.com/assets/9952056/20825914/aa57e9b6-b867-11e6-85e6-03c9a8afea2a.png)

![image](https://cloud.githubusercontent.com/assets/9952056/20826036/8937f04a-b868-11e6-9ba2-07c3062282ec.png)

**Comment by debojyoti-majumder** [comment]
I can start looking into this, can @defnax give me some idea about on which module/files I should be looking into?

**Comment by cavebeat** [comment]
@debojyoti-majumder 
https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/pqi/authssl.cc
https://github.com/RetroShare/RetroShare/blob/32db2800c7d811070ab707823bb266635c406f28/libretroshare/src/pgp/pgphandler.cc

I'd say you can start there. 

To improve communication you should join us in the devel chatroom inside RetroShare. contact me. 

Thanks for your offer.

**Comment by debojyoti-majumder** [comment]
Thanks @defnax. I will try to make a build and first(I have only cloned it.) and you know.

**Comment by cavebeat** [comment]
atm https://github.com/public/OpenPGP-SDK is in use. 
https://www.ietf.org/mail-archive/web/openpgp/current/msg00469.html
It's already dated and unmaintained, and i guess by far RetroShare has put a lot of time and bughuntung into it to fix problems. https://github.com/RetroShare/RetroShare/tree/master/openpgpsdk/src
I am not sure if openPGP-SDK can do ECC Public Key crypto. 

https://blog.netbsd.org/tnf/entry/netpgp is based on openPGP-SDK and somewhat a successor of it. 
http://www.netpgp.com/ https://www.netbsd.org/~agc/netpgp_2009.pdf
netpgp is also umaintained nowadays. 

GPGME is just a wrapper of the exec and not a library. 

my guess would be NaCl. 
NaCl (pronounced "salt") is a new easy-to-use high-speed software library for network communication, encryption, decryption, signatures, etc. 
https://nacl.cr.yp.to/index.html

adding NaCL for Public-Key Crypto (and ripping out openPGP-SDK) in RetroShare seems to be a tough goal for me. Or have i misunderstood the issue and the goal of "easy short RetroShare ID"

What's your thought about it? 

btw, i am not defnax!

**Comment by csoler** [comment]
- GPGME is a nightmare in terms of efficiency since the library forks to gpg on every call. That's why is has been dropped.
- yes openpgp-sdk is old and I have cleaned/improved/debugged it when I ported it to RS. It's not an ideal solution for many reasons in particular because it's hard to read and maintain and is probably full of potential bugs
- going from openPGP-sdk to NaCl is not a difficult thing to do. The recipe is to implement a new interface file such as the one we have now for RS-to-OpenPGP-SDK. This file is libretroshare/pgp/pgphandler.cc. This file is the only place in the whole RS code where openpgp-sdk is explicitly referred to.

**Comment by lulcat** [comment]
I also would like to add, does openPGP do *25519 currently? gpg (Gnupg) does, and currently, it's generally seen as the only dependable ECC option (non-NIST/NSA). I see retroshare only uses RSA which in something like x509 is obviously broken, but by itself ok.. still not provably broken but ...

**Comment by defnax** [comment]
done with short id

**Comment by sehraf** [comment]
Short ids are less secure than long ones. I'd still prefer ecc.

**Comment by csoler** [comment]
Short IDs have nothing to do with ECC. They contain the ID of the SSL key instead of the public PGP key, that's all. You could use ECC with or without short IDs if it was available. Now that we have short IDs, the need to switch to ECC is far less critical (as soon as we can trust RSA-2048/4096).

@sehraf: I dont think that the security is reduced. If you think so, please elaborate.

**Comment by sehraf** [comment]
With "less secure" I mean that the PGP key is replaced by the ssl is as a trust anchor.
The id is 128 bit long (no idea if it's completely randomly chosen, what is its entropy? ) while the key can have different sizes (with longer being supposed to be more secure). 

To get this right: I'm not saying that it is insecure, just that you loose the advantage of a large/long PGP key.

**Comment by csoler** [comment]
During the handshake, the PGP key is only here to validate the hash of the SSL public key using a RSA signature. In the new format, you directly give this hash. So the information is quite the same. In both cases, an attack against this would require to form a SSL 2048bits key that hash the same hash.
What sharing the PGP key changes is that is allows connections from other SSL keys signd with that same PGP public key even before the frst connection. In the new system, the peer sends his pgp public key after the first connection. As an additional check (which is not really necessary) the fingerprint of this key is compared to the fingerprint that is in the short invite.

**Comment by sehraf** [comment]
OK, then I've mixed up things, thanks for the clarification.
