### ISSUE TITLE
Reproducible Builds // OBS a bad Idea

### ISSUE THREAD

**Issue by HulaHoopWhonix** [RetroShare/RetroShare#509]
IMHO having project binary builds on an online build server is a bad move especially in absence of a reproducible build system. You cannot rely on a cloud server to not work against your interests and that of your users. The Certificate Authority/HTTPS is badly broken system and not a guarantee against nation states trying to poison binaries.

I think that at the very least you should run your own build infrastructure until repro builds are realized so you can verify no one messed with binaries you distribute. Within the next release of Debian, reproducible binaries will be a must for inclusion in their repositories.

**Comment by cavebeat** [comment]
hmm, i'm no expert for reproducible builds. 
https://github.com/RetroShare/RetroShare/releases <-- but jessie builds are already released manually. I guess we can improve their. 
Debian on OBS is just for nightly and because it's possible to build for debian. 

I/we should update the homepage to reflect this
