### ISSUE TITLE
Sent my Retro-share Certificate to my friend when they enter in they get a missing check-sum error

### ISSUE THREAD

**Issue by TauRexx1** [RetroShare/RetroShare#594]
Sent my Retro-share Certificate to my friend when they enter in they get a missing check-sum error, we are both using 0.6.1 53e26983 QT version 5.5 how do I correct this issue?

**Comment by csoler** [comment]
people sometimes send their PGP key instead of their RS certificate. Would it explain the problem in your case? The certificate is a plain block of radix data, which you will find in the connect wizard.

**Comment by TauRexx1** [comment]
Hello csoler, thank you for the response, I used the add friend method of sending invitation by web-mail provider in the confirmation area which has my public cert, from what I can tell the info is correct but when my friend attempts to enter my cert data into his listing the missing check sum error appears any and all help with this matter is greatly appreciated.

**Comment by csoler** [comment]
Can your certificate be somehow corrupted by the mail service? I remember that German users had problems because of automated convertion of two 's' into the single German 'ss' character. I dont believe that RS produces a certificate without checksum in the first place. Otherwise you can try to compare what the email contains with the vanilla certificate produced by option 1 "Enter the certificate manually". This may help us fix some possible bug in the transmission of the cert to the email service.

**Comment by TauRexx1** [comment]
Hello and very good point I take a closer look at the mail service and then
try a direct approach and manually install my cert in my friends machine to
see if that makes a difference, again thank you for your suggestion.
