### ISSUE TITLE
App features

### ISSUE THREAD

**Issue by ghost** [RetroShare/RetroShare#604]
Is there possibility to load all messages in channels, forums and publications?
Is there possibility to check that file is seeding and get a counter of currently online seeders?

**Comment by felisucoibi** [comment]
Is there possibility to load all messages in channels, forums and publications?
YES, just subscribe.
Is there possibility to check that file is seeding and get a counter of currently online seeders?
YES, when you search for a file it tells you how many seeds in search results.

Please mark as fixed, because is not a bug but a question.
