### ISSUE TITLE
Provide AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [RetroShare/RetroShare#684]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

Here is an an experimental AppImage:
https://bintray.com/probono/AppImages/RetroShare06/_latestVersion#files

You can generate it yourself on any deb-based system:

```
wget -c "https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe"
bash Recipe RetroShare
```

It will download RetroShare from the ppa and convert it to an AppImage. For this, it will use [this yml file](https://github.com/probonopd/AppImages/blob/master/recipes/meta/RetroShare.yml) that defines the ppa to AppImage conversion, very few lines of code.

**Comment by csoler** [comment]
And what happens when a critical security bug is found on one of the standard crypto-library we use, such as openssl?

**Comment by probonopd** [comment]
Short answer: If a fix is in `trusty-updates`, then you re-run the script to get a fixed AppImage. Longer answer: It would be desirable to make it work with the system's openssl and not bundle that library inside the AppImage.

See this great blog post:
http://www.bruijntjes.net/blog/post/8c504e2f4a79ff837221d77183c88d00

**Comment by akintranslator** [comment]
I just would like to let you know this app image is working on debian 8.8.0 64 bit system.
Best regards

**Comment by probonopd** [comment]
@csoler if you use the [Open Build Service to generate the AppImage](https://git.io/obs-ai), then it will be automatically re-generated once there is an update to one of the ingredient libraries.

**Comment by G10h4ck** [comment]
We are now distributing RetroShare appimage trought OBS, thanks @probonopd for your support!

**Comment by probonopd** [comment]
A download link on README.md might be a good idea :-)

**Comment by probonopd** [comment]
Now getting `FATAL: .DirIcon is missing in /tmp/.mount_BeingT4nhkBu` - are you sure `.DirIcon` is there in the AppImage?

Reference: https://github.com/AppImage/appimage.github.io/pull/1717

**Comment by ThibaultLemaire** [comment]
Hi,

I have tested the AppImage (`retroshare-gui-0-Build22.8.glibc2.17-x86_64.AppImage`) on `NixOS 20.09 (Nightingale) x86_64` and on `Ubuntu 20.04.1 LTS x86_64`. Both are able to run the AppImage, but neither can subsequently establish connectivity.

The issue turned out to be a missing `bdboot.txt` as this was a fresh install and I did not copy an existing profile. I think the `bdboot.txt` file should be included in the AppImage. (If at all possible, I'm not familiar with the inner workings of the AppImage format, but I think it uses some kind of `chroot` to make the embedded libraries available to the executable? Maybe it could make `/usr/share/retroshare/bdboot.txt` available in the same manner.)
