### ISSUE TITLE
IP blacklist doesn't work.

### ISSUE THREAD

**Issue by bauermann** [RetroShare/RetroShare#71]
I manually added 194.228.20.255/24 to the IP blacklist, but looking at network traffic with Wireshark I see my machine receiving UDP packets from that network (can't be avoided, I suppose), but to my surprise happily **SENDING BACK** UDP packets to them (yes, plural!).

This is **VERY** dangerous, since those machines are known to be run by malicious actors. What if they have a remote exploit against RetroShare or some of its libs? RetroShare shouldn't do any processing of packets coming from malicious machines. It should drop them at the earliest opportunity without even reading its contents.

This is extremely serious, and needs to be fixed urgently.

This is on Ubuntu Vivid, with package RetroShare06 version 0.6.0-1.20150816.9734f32a~vivid, obtained via the RetroShare PPA.

**Comment by csoler** [comment]
Actually the DHT keeps exchanging UDP packets with these actors, since they run a DHT themselves. The data that you see is not RS network (encrypted) data. It's just DHT data. The blacklist acts at a higher level when your RS tries to connect to one of these IPs using SSL and blocks these connexions.
So no need to worry! But thx for keeping a close look at what's going on. It can be pretty helpful.

**Comment by csoler** [comment]
also, it's very important that the DHT (on RS side) sees the activity of these IPs since this is precisely what makes it report them as masquerading IPs.

**Comment by bauermann** [comment]
Thanks responding so quickly!

I still think it's a security risk. What if there's an exploitable bug in RetroShare's DHT implementation? 

For example: there could be a buffer overflow when parsing DHT data that could allow these guys to remotely execute code on the computer.

**Comment by csoler** [comment]
That's a possibility. I'll have a look at the code tonight, just in case I see something that would ring the bell. Because DHT packets have limited length, it's not so easy to use them to buffer overflow. But you're right that we take this seriously. Thx for mentioning it.

**Comment by bauermann** [comment]
Regarding your point about needing to see their activity, that would only be needed before they are flagged as masquerading IPs. At the moment they are identified and added to the blacklist, then they're known malicious machines and their packets can (and should, IMHO) be dropped on sight.

There could be a timeout after which IPs automatically added to the blacklist would be removed, but if an IP or IP range was manually added there's no need to ever see any activity from them.

**Comment by bauermann** [comment]
I'm interested in trying to implement this feature (i.e., dropping DHT packets coming from blacklisted IPs as early as possible). Would you accept a pull request for that? Do you think it's feasible?

**Comment by csoler** [comment]
well, given that the DHT cannot make the difference between good and bad IPs, dropping them is a bit too conservative. It would allow an attacker to completely desactivate the DHT by spamming masquerading responses. I don't think this is a good idea.

**Comment by bauermann** [comment]
Ok. I believe issue can be closed, then.

**Comment by cavebeat** [comment]
libbitDHT could ask random Hashes which do not exist. If there is some ip responding with this non-existing hashes (4 out of 5) it could be blocked because it trys to spoof with a siblings attack. thats for me a way to find out bad ips which should be blocked.

**Comment by csoler** [comment]
I think that cave has a point. In terms of modifications, it's quite easy to do:
- add a few random DHT hashes to the pool of requests in DHT code, and flag them a fake
- whenever such hashes are answered, immediately report the IP to be masquerading (using the existing system)
  I think it's quite a simple modification to do.

@bauermann : are you willing to implement this? This is quite consistent with existing code since it doesn't require any talking between libretroshare and libbitdht.

**Comment by bauermann** [comment]
@csoler Yes, I am. I'll probably be able to start only on the weekend, though.

I'm a bit confused about the second step you mentioned above (report the IP to be masquerading): what you are saying is that the DHT code will be able to add to the blacklist, but will keep processing DHT packets from blacklisted IPs?

**Comment by csoler** [comment]
There's two blacklists: 
- one hold by the DHT, that only the DHT can modify. That list is accessed by libretroshare and used in the p3BanList service
- one held by p3BanList and shared with friends. This list is filled with information from various sources: the user, the DHT and friends.

Adding some fake ids in DHT will automatically increase the DHT list size, which will be then automatically propagated to p3BanList.

Now, I thought a bit about using fake IDs. You cannot use purely random IDs, since an attacker would receive exactly once each fake ID, and would be able to perform statistics. Only real IDs, requested by multiple friends would generate multiple hits. So we need that fake ids are requested as often as real ids, from as many different peers (just like real ids).

For this I suggest that you do this:
- pick a real DHT id at random (in the list of existing DHT ids from real friends)
- compute a SHA1 hash of that ID, and use this to form the corresponding fake ID 

=> the real ID cannot be recovered from the fake ID, unless you already know it (so it's useless)
=> it's not possible to find out whether an ID is fake or real, unless you know the real ID that matches it
=> all peers sharing a friend will generate the same fake ID from it.

Then you add up that fake ID to the pool of DHT requests, with a flag that says it's fake. Each time you get a request response, check the ID. If it's fake, flag the response ID as bad! That should be pretty efficient.

**Comment by csoler** [comment]
any news about this?

**Comment by bauermann** [comment]
Sorry, not much. I started familiarizing myself with the code, but haven't made any changes yet. Unfortunately I've not been able to dedicate much time to it, so I'm moving slowly. :-/

I don't want to hold anything back, so if you think it's simpler and faster if you do it yourself, I wouldn't mind. But if you don't mind the wait I'll keep working on it.

**Comment by csoler** [comment]
No worries! It always takes time to understand the code. I'm actually very glad to see someone willing to contribute. Do not hesitate to send me some questions if you need.

**Comment by bauermann** [comment]
I actually do have one which is probably a bit stupid: why would my suggestion of having the DHT drop packets by blacklisted IPs allow attackers to disable the DHT by spamming masquerading responses, but your idea doesn't have the same problem?

**Comment by csoler** [comment]
Because the blacklist is fed from DHT statistics, so we need to keep them sending packets.
If you drop packets from blacklisted IPs, an attacker can associate every known SSL id he knows with some single IP and have have the real IPs (which would probably less than 50% of the time be the correct response).
If you just ask for fake DHT ids with the same timing statistics (same frequency, same interval, etc) than normal real IDs, the attacker cannot know if the DHT ID is fake or not, but RS will know that the response comes for a fake ID => the attacker is easily located without leaking information, and without risking to block an existing true DHT ID.

**Comment by csoler** [comment]
Actually, IPs that are detected using fake IDs are 100% reliable to be bad IPs. So yes, you can then ignore them totally. But that needs to be taken care off in the DHT code. These IPs should still be passed on to the rest of the program (as other banned IPs) and also put in a special list that is tested everytime a DHT request needs to be answered.

Also, this list can be used to re-enable (or not disable) IPs from real peers, which pair with attacker's IPs for a given ID. 

We could as well use libretroshare to send back info to the DHT to validate some IPs, since friends exchange their IPs using a secure channel.

In the end, the DHT would get a very accurate list of attacker's IPs.

**Comment by cavebeat** [comment]
hi @bauermann 
how is your progress?
do you need connectivity to the hive, a bootstrapping peer to the devel community?
br cave

**Comment by csoler** [comment]
I was about to ask. I've got time to do this during the week.

**Comment by bauermann** [comment]
Feel free to do it, then. Unfortunately I got extremely busy with work these past two weeks (worked this weekend, even) and was not able to dedicate time to this. :-(

**Comment by csoler** [comment]
That's fine. Feel free to come back when you have time. We really need contributors.
