### ISSUE TITLE
Android: The --ndk-dir argument is no longer supported.

### ISSUE THREAD

**Issue by inferrna** [RetroShare/RetroShare#855]
Having latest stable ndk, sdk-tools and android-studio got this error when run
./android-prepare-toolchain.sh

**Comment by G10h4ck** [comment]
Someone already reported that to me, ATM the latest NDK and SDK are not supported either because incompatibility with stable Qt or because the script is not yet compatible with newer versions, as of today I recommend to use

android-sdk 24.4.1
android-ndk 10e
Android API level 18
Retroshare from https://github.com/G10h4ck/RetroShare/tree/qmlapp_pex_alpha

For android stuff please refer to my fork in the branch qmlapp_pex_alpha because a bunch of fixes has been done there and will be fixed here too as soon as I prepare a pull request and it get reviewed and merged
https://github.com/G10h4ck/RetroShare/tree/qmlapp_pex_alpha

**Comment by G10h4ck** [comment]
should be fixed now
